version: "2"

services:
  mongodb:
    image: mongo:3.0.4
    command: mongod --smallfiles
    ports:
      - "27017:27017"
  eureka:
    build: eureka/.
    working_dir: /
    links:
      - config-server
    ports:
      - "8761:8761"
    entrypoint: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar
  authserver:
    build: authserver/.
    working_dir: /
    links:
      - config-server
    ports:
      - "9999:9999"
    entrypoint: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar
  config-server:
    build: config-server/.
    working_dir: /
    ports:
      - "8888:8888"
  catalog:
    build: catalog/.
    working_dir: /
    links:
      - config-server
      - authserver
      - eureka
    ports:
      - "8080:8080"
    entrypoint: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar
  gateway:
    build: api-gateway/.
    working_dir: /
    links:
      - config-server
      - authserver
      - eureka
    ports:
      - "9000:9000"
    entrypoint: ./wait-for-it.sh config-server:8888 -t 60 --
    command: java -Dspring.profiles.active=docker -jar /app.jar